"""T16_offer_ab_models

Revision ID: 3daaf783771d
Revises: 86d5b2971e22
Create Date: 2025-12-27 00:54:45.061724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '3daaf783771d'
down_revision: Union[str, None] = '86d5b2971e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(table_name):
    bind = op.get_bind()
    insp = inspect(bind)
    return insp.has_table(table_name)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('experiment'):
        op.create_table('experiment',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('start_at', sa.DateTime(), nullable=True),
        sa.Column('end_at', sa.DateTime(), nullable=True),
        sa.Column('variants', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_experiment_key'), 'experiment', ['key'], unique=False)
        op.create_index(op.f('ix_experiment_tenant_id'), 'experiment', ['tenant_id'], unique=False)
    
    if not table_exists('offer'):
        op.create_table('offer',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('cost_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('cost_value', sa.Float(), nullable=False),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('eligibility_criteria', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_offer_tenant_id'), 'offer', ['tenant_id'], unique=False)
    
    if not table_exists('experimentassignment'):
        op.create_table('experimentassignment',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('experiment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('variant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('assigned_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_experimentassignment_experiment_id'), 'experimentassignment', ['experiment_id'], unique=False)
        op.create_index(op.f('ix_experimentassignment_player_id'), 'experimentassignment', ['player_id'], unique=False)
        op.create_index(op.f('ix_experimentassignment_tenant_id'), 'experimentassignment', ['tenant_id'], unique=False)
    
    if not table_exists('offerdecisionrecord'):
        op.create_table('offerdecisionrecord',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('trigger_event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('offer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('experiment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('variant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('deny_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('score_details', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
        sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_offerdecisionrecord_player_id'), 'offerdecisionrecord', ['player_id'], unique=False)
        op.create_index(op.f('ix_offerdecisionrecord_tenant_id'), 'offerdecisionrecord', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipping drop to avoid accidental data loss during dev cycle
    pass
    # ### end Alembic commands ###
