"""T17_dispute_models

Revision ID: c553520d78cd
Revises: 3daaf783771d
Create Date: 2025-12-27 01:02:09.969919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'c553520d78cd'
down_revision: Union[str, None] = '3daaf783771d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(table_name):
    bind = op.get_bind()
    insp = inspect(bind)
    return insp.has_table(table_name)

def get_indexes(table_name):
    bind = op.get_bind()
    insp = inspect(bind)
    return [i['name'] for i in insp.get_indexes(table_name)]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Update Dispute table (It already exists from payment_models.py but schema changed significantly)
    # Check if 'dispute' exists. If not, creating it fresh.
    # The 'payment_models.py' defined it, but if it wasn't migrated before?
    # In fresh DB test, it fails because 'dispute' table doesn't exist yet?
    # Let's check history. 'dispute' was NEVER created in previous migrations in the chain above!
    # It was defined in python file but no migration created it?
    # Ah, 'payment_models' is imported in env.py, so autogenerate SEES it.
    # But previous migrations didn't include it. So autogenerate thinks it's there? No.
    # If table doesn't exist in DB, autogenerate should say 'add_table'.
    # The error 'NoSuchTableError: dispute' in batch_alter_table means we are trying to alter a table that doesn't exist.
    
    if not table_exists('dispute'):
        # Create fresh
        op.create_table('dispute',
            sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('amount', sa.Float(), nullable=False),
            sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('evidence_files', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('resolved_at', sa.DateTime(), nullable=True),
            sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_dispute_player_id'), 'dispute', ['player_id'], unique=False)
        op.create_index(op.f('ix_dispute_status'), 'dispute', ['status'], unique=False)
        op.create_index(op.f('ix_dispute_transaction_id'), 'dispute', ['transaction_id'], unique=False)
    else:
        # Alter existing (if it came from some other path, unlikely in fresh DB but possible in existing env)
        with op.batch_alter_table('dispute', schema=None) as batch_op:
            # Add new columns
            batch_op.add_column(sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
            batch_op.add_column(sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
            batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False, server_default='0.0'))
            batch_op.add_column(sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='USD'))
            batch_op.add_column(sa.Column('evidence_files', sa.JSON(), nullable=True))
            batch_op.add_column(sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
            
            # Drop old columns
            # We wrap in try/except or check if column exists, but batch mode handles 'drop' gracefully-ish.
            # But let's assume if we are altering, we are converting from the 'PaymentIntent' version.
            # Columns to drop: evidence, payment_intent_id, amount_disputed
            batch_op.drop_column('evidence')
            batch_op.drop_column('payment_intent_id')
            batch_op.drop_column('amount_disputed')
            
            # Indexes
            # Check if index exists
            bind = op.get_bind()
            insp = inspect(bind)
            indexes = [i['name'] for i in insp.get_indexes('dispute')]
            if 'ix_dispute_payment_intent_id' in indexes:
                batch_op.drop_index('ix_dispute_payment_intent_id')
            
            # Create new indexes
            if 'ix_dispute_player_id' not in indexes:
                batch_op.create_index(op.f('ix_dispute_player_id'), ['player_id'], unique=False)
            if 'ix_dispute_status' not in indexes:
                batch_op.create_index(op.f('ix_dispute_status'), ['status'], unique=False)
            if 'ix_dispute_transaction_id' not in indexes:
                batch_op.create_index(op.f('ix_dispute_transaction_id'), ['transaction_id'], unique=False)

    # 2. AffiliateClawback
    if not table_exists('affiliateclawback'):
        op.create_table('affiliateclawback',
            sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('affiliate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('original_commission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('dispute_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('amount_reversed', sa.Float(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['dispute_id'], ['dispute.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_affiliateclawback_affiliate_id'), 'affiliateclawback', ['affiliate_id'], unique=False)
        op.create_index(op.f('ix_affiliateclawback_tenant_id'), 'affiliateclawback', ['tenant_id'], unique=False)

    if table_exists('table_game'):
        indexes = get_indexes('table_game')
        if 'ix_table_game_tenant_id' in indexes:
            op.drop_index('ix_table_game_tenant_id', table_name='table_game')
        op.drop_table('table_game')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
