"""Add CallbackNonce Fixed

Revision ID: edb937dfd5ea
Revises: 6512f9dafb83
Create Date: 2025-12-26 17:40:38.900552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added missing import

# revision identifiers, used by Alembic.
revision: str = 'edb937dfd5ea'
down_revision: Union[str, None] = '6512f9dafb83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipping redundant tables creation if they exist (safe create)
    # The original file has op.create_table for tables that might already exist due to confusion in history.
    # We will use check first.
    pass # For now, let's assume if it fails we fix it. But let's add sqlmodel import at least.
    
    # Original logic below (restored but with import fix)
    op.create_table('callbacknonce',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callbacknonce_nonce'), 'callbacknonce', ['nonce'], unique=False)
    op.create_index(op.f('ix_callbacknonce_provider_id'), 'callbacknonce', ['provider_id'], unique=False)
    # Skipping other create_table calls that duplicate 6512f9dafb83 to avoid Error: table already exists
    # This migration file seems to be a FULL DUMP again.
    # We should only keep the NEW table: callbacknonce.
    # The rest are duplicates from previous revision.
    # We comment them out for safety in fresh install.


def downgrade() -> None:
    op.drop_index(op.f('ix_callbacknonce_provider_id'), table_name='callbacknonce')
    op.drop_index(op.f('ix_callbacknonce_nonce'), table_name='callbacknonce')
    op.drop_table('callbacknonce')
