FROM node:20-alpine AS build

RUN node -v

WORKDIR /app

COPY package.json yarn.lock ./
RUN test -f yarn.lock
RUN yarn install --frozen-lockfile --non-interactive

COPY . .

ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL

RUN yarn build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
