from .domain.admin import *
from .domain.feature_flags import *
from .domain.simulation import *
from .domain.settings import *
from .domain.cms import *
from .domain.risk import *
from .domain.affiliate import *
from .domain.crm import *
from .domain.support import *
from .domain.system import *
from .domain.kyc import *
from .domain.reports import *
