export const ERROR_CODES = {
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_UNVERIFIED: 'AUTH_UNVERIFIED',
  VERIFY_EMAIL_REQUIRED: 'VERIFY_EMAIL_REQUIRED',
  VERIFY_SMS_REQUIRED: 'VERIFY_SMS_REQUIRED',
  COMPLIANCE_AGE_REQUIRED: 'COMPLIANCE_AGE_REQUIRED',
  GAME_LAUNCH_FAILED: 'GAME_LAUNCH_FAILED',
  GAME_PROVIDER_DOWN: 'GAME_PROVIDER_DOWN',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  WALLET_INSUFFICIENT: 'WALLET_INSUFFICIENT',
  UNKNOWN: 'UNKNOWN',
};

export const buildOk = (data) => ({ ok: true, data });
export const buildError = (code, message, meta = {}) => ({
  ok: false,
  error: { code, message, meta },
});
