"""Generate a baseline Alembic migration from current SQLModel metadata.

This writes explicit op.create_table(...) calls into the existing baseline revision
(24e894ecb377) so prod/staging can rely solely on Alembic.

Usage:
  cd backend
  python scripts/generate_baseline_migration.py

This script is intended to be run by CI/devs and committed.
"""

from __future__ import annotations

from pathlib import Path


def main() -> None:
    import sys
    sys.path.append(str(Path(__file__).resolve().parents[1]))
    from alembic.autogenerate import api as ag_api
    from alembic.migration import MigrationContext
    import sqlalchemy as sa

    from app.models.sql_models import SQLModel

    # Offline autogenerate: compare against empty DB
    ctx = MigrationContext.configure(
        dialect_name="postgresql",
        opts={
            "target_metadata": SQLModel.metadata,
            "compare_type": True,
        },
    )

    script = ag_api.produce_migrations(ctx, SQLModel.metadata)

    # Render Python code for ops
    upgrade_lines: list[str] = []
    downgrade_lines: list[str] = []

    # Alembic renderers expect a dialect; provide a generic PG dialect.
    dialect = sa.dialects.postgresql.dialect()

    for op_obj in script.upgrade_ops.ops:
        upgrade_lines.append(ag_api.render_python_code(op_obj, render_as_batch=False, dialect=dialect).rstrip())

    for op_obj in script.downgrade_ops.ops:
        downgrade_lines.append(ag_api.render_python_code(op_obj, render_as_batch=False, dialect=dialect).rstrip())

    upgrade_code = "\n".join([l for l in upgrade_lines if l.strip()]) or "pass"
    downgrade_code = "\n".join([l for l in downgrade_lines if l.strip()]) or "pass"

    baseline_path = Path(__file__).resolve().parents[1] / "alembic" / "versions" / "24e894ecb377_baseline.py"
    text = baseline_path.read_text()

    def replace_block(src: str, fn: str, body: str) -> str:
        import re

        pattern = re.compile(rf"def {fn}\(\) -> None:\n(\s+)(?:#.*\n)?\s*pass\n", re.MULTILINE)
        m = pattern.search(src)
        if not m:
            raise RuntimeError(f"Could not find placeholder 'pass' in {fn}()")
        indent = m.group(1)
        body_indented = "\n".join(indent + line if line.strip() else line for line in body.splitlines())
        return pattern.sub(f"def {fn}() -> None:\n{indent}# ### commands auto generated by Alembic - please adjust! ###\n{body_indented}\n{indent}# ### end Alembic commands ###\n", src)

    text = replace_block(text, "upgrade", upgrade_code)
    text = replace_block(text, "downgrade", downgrade_code)

    baseline_path.write_text(text)
    print(f"Wrote baseline migration: {baseline_path}")


if __name__ == "__main__":
    main()
