"""Add Game Models

Revision ID: 079ecae04f90
Revises: f9f022e796d9
Create Date: 2025-12-26 17:27:42.172432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '079ecae04f90'
down_revision: Union[str, None] = 'f9f022e796d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gameasset')
    op.drop_table('gameconfigversion')
    op.drop_table('featureflag')
    op.drop_table('financesettings')
    op.drop_table('game')
    op.drop_index('ix_adminuser_email', table_name='adminuser')
    op.drop_index('ix_adminuser_tenant_id', table_name='adminuser')
    op.drop_table('adminuser')
    op.drop_index('ix_ledger_tx_player_created_at', table_name='ledgertransaction')
    op.drop_index('ix_ledger_tx_provider_ref', table_name='ledgertransaction')
    op.drop_index('ix_ledger_tx_tx_id', table_name='ledgertransaction')
    op.drop_index('ix_ledgertransaction_player_id', table_name='ledgertransaction')
    op.drop_index('ix_ledgertransaction_tenant_id', table_name='ledgertransaction')
    op.drop_index('ix_ledgertransaction_tx_id', table_name='ledgertransaction')
    op.drop_table('ledgertransaction')
    op.drop_table('reconciliationreport')
    op.drop_index('ix_payoutattempt_idempotency_key', table_name='payoutattempt')
    op.drop_index('ix_payoutattempt_provider', table_name='payoutattempt')
    op.drop_index('ix_payoutattempt_provider_event_id', table_name='payoutattempt')
    op.drop_index('ix_payoutattempt_status', table_name='payoutattempt')
    op.drop_index('ix_payoutattempt_tenant_id', table_name='payoutattempt')
    op.drop_index('ix_payoutattempt_withdraw_tx_id', table_name='payoutattempt')
    op.drop_table('payoutattempt')
    op.drop_table('bonus')
    op.drop_table('affiliate')
    op.drop_table('contentpage')
    op.drop_index('ix_walletbalance_updated_at', table_name='walletbalance')
    op.drop_table('walletbalance')
    op.drop_table('chargebackcase')
    op.drop_index('ux_tx_player_id_idempotency_key_not_null', table_name='transaction', sqlite_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ux_tx_provider_event_not_null', table_name='transaction', sqlite_where=sa.text('provider_event_id IS NOT NULL'))
    op.drop_table('transaction')
    op.drop_table('auditlog')
    op.drop_index('ix_table_game_tenant_id', table_name='table_game')
    op.drop_table('table_game')
    op.drop_table('approvalrequest')
    op.drop_table('player')
    op.drop_table('riskrule')
    op.drop_index('ix_reconciliation_runs_idempotency_key', table_name='reconciliation_runs')
    op.drop_index('ix_reconciliation_runs_provider', table_name='reconciliation_runs')
    op.drop_index('ix_reconciliation_runs_status', table_name='reconciliation_runs')
    op.drop_index('ux_recon_runs_provider_idempotency_key', table_name='reconciliation_runs', sqlite_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_table('reconciliation_runs')
    op.drop_index('ix_auditevent_action', table_name='auditevent')
    op.drop_index('ix_auditevent_actor_user_id', table_name='auditevent')
    op.drop_index('ix_auditevent_request_id', table_name='auditevent')
    op.drop_index('ix_auditevent_resource_id', table_name='auditevent')
    op.drop_index('ix_auditevent_resource_type', table_name='auditevent')
    op.drop_index('ix_auditevent_result', table_name='auditevent')
    op.drop_index('ix_auditevent_tenant_id', table_name='auditevent')
    op.drop_index('ix_auditevent_timestamp', table_name='auditevent')
    op.drop_table('auditevent')
    op.drop_index('ix_reconciliation_findings_finding_type', table_name='reconciliation_findings')
    op.drop_index('ix_reconciliation_findings_player_id', table_name='reconciliation_findings')
    op.drop_index('ix_reconciliation_findings_provider', table_name='reconciliation_findings')
    op.drop_index('ix_reconciliation_findings_provider_event_id', table_name='reconciliation_findings')
    op.drop_index('ix_reconciliation_findings_provider_ref', table_name='reconciliation_findings')
    op.drop_index('ix_reconciliation_findings_severity', table_name='reconciliation_findings')
    op.drop_index('ix_reconciliation_findings_status', table_name='reconciliation_findings')
    op.drop_index('ix_reconciliation_findings_tenant_id', table_name='reconciliation_findings')
    op.drop_index('ix_reconciliation_findings_tx_id', table_name='reconciliation_findings')
    op.drop_table('reconciliation_findings')
    op.drop_table('apikey')
    op.drop_table('supportticket')
    op.drop_index('ix_tenant_name', table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('features', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('daily_deposit_limit', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('daily_withdraw_limit', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('payout_retry_limit', sa.INTEGER(), nullable=True),
    sa.Column('payout_cooldown_seconds', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenant_name', 'tenant', ['name'], unique=False)
    op.create_table('supportticket',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('player_id', sa.VARCHAR(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('priority', sa.VARCHAR(), nullable=False),
    sa.Column('messages', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apikey',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('key_hash', sa.VARCHAR(), nullable=False),
    sa.Column('scopes', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_findings',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=True),
    sa.Column('player_id', sa.VARCHAR(), nullable=True),
    sa.Column('tx_id', sa.VARCHAR(), nullable=True),
    sa.Column('provider_event_id', sa.VARCHAR(), nullable=True),
    sa.Column('provider_ref', sa.VARCHAR(), nullable=True),
    sa.Column('finding_type', sa.VARCHAR(), nullable=False),
    sa.Column('severity', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('raw', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reconciliation_findings_tx_id', 'reconciliation_findings', ['tx_id'], unique=False)
    op.create_index('ix_reconciliation_findings_tenant_id', 'reconciliation_findings', ['tenant_id'], unique=False)
    op.create_index('ix_reconciliation_findings_status', 'reconciliation_findings', ['status'], unique=False)
    op.create_index('ix_reconciliation_findings_severity', 'reconciliation_findings', ['severity'], unique=False)
    op.create_index('ix_reconciliation_findings_provider_ref', 'reconciliation_findings', ['provider_ref'], unique=False)
    op.create_index('ix_reconciliation_findings_provider_event_id', 'reconciliation_findings', ['provider_event_id'], unique=False)
    op.create_index('ix_reconciliation_findings_provider', 'reconciliation_findings', ['provider'], unique=False)
    op.create_index('ix_reconciliation_findings_player_id', 'reconciliation_findings', ['player_id'], unique=False)
    op.create_index('ix_reconciliation_findings_finding_type', 'reconciliation_findings', ['finding_type'], unique=False)
    op.create_table('auditevent',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('request_id', sa.VARCHAR(), nullable=False),
    sa.Column('actor_user_id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(), nullable=True),
    sa.Column('result', sa.VARCHAR(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auditevent_timestamp', 'auditevent', ['timestamp'], unique=False)
    op.create_index('ix_auditevent_tenant_id', 'auditevent', ['tenant_id'], unique=False)
    op.create_index('ix_auditevent_result', 'auditevent', ['result'], unique=False)
    op.create_index('ix_auditevent_resource_type', 'auditevent', ['resource_type'], unique=False)
    op.create_index('ix_auditevent_resource_id', 'auditevent', ['resource_id'], unique=False)
    op.create_index('ix_auditevent_request_id', 'auditevent', ['request_id'], unique=False)
    op.create_index('ix_auditevent_actor_user_id', 'auditevent', ['actor_user_id'], unique=False)
    op.create_index('ix_auditevent_action', 'auditevent', ['action'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('provider', sa.VARCHAR(length=64), nullable=False),
    sa.Column('window_start', sa.DATETIME(), nullable=False),
    sa.Column('window_end', sa.DATETIME(), nullable=False),
    sa.Column('dry_run', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(length=128), nullable=True),
    sa.Column('stats_json', sa.TEXT(), nullable=True),
    sa.Column('error_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_recon_runs_provider_idempotency_key', 'reconciliation_runs', ['provider', 'idempotency_key'], unique=1, sqlite_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_index('ix_reconciliation_runs_status', 'reconciliation_runs', ['status'], unique=False)
    op.create_index('ix_reconciliation_runs_provider', 'reconciliation_runs', ['provider'], unique=False)
    op.create_index('ix_reconciliation_runs_idempotency_key', 'reconciliation_runs', ['idempotency_key'], unique=False)
    op.create_table('riskrule',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('condition', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('balance_real', sa.FLOAT(), nullable=False),
    sa.Column('balance_bonus', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('kyc_status', sa.VARCHAR(), nullable=False),
    sa.Column('risk_score', sa.VARCHAR(), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('registered_at', sa.DATETIME(), nullable=False),
    sa.Column('balance_real_available', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('balance_real_held', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvalrequest',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('related_entity_id', sa.VARCHAR(), nullable=False),
    sa.Column('requester_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_game',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('min_bet', sa.FLOAT(), nullable=False),
    sa.Column('max_bet', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_table_game_tenant_id', 'table_game', ['tenant_id'], unique=False)
    op.create_table('auditlog',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('admin_id', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('module', sa.VARCHAR(), nullable=False),
    sa.Column('target_id', sa.VARCHAR(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('player_id', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('method', sa.VARCHAR(), nullable=True),
    sa.Column('provider_tx_id', sa.VARCHAR(), nullable=True),
    sa.Column('balance_after', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('state', sa.VARCHAR(), server_default=sa.text('("created")'), nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('provider_event_id', sa.VARCHAR(), nullable=True),
    sa.Column('review_reason', sa.TEXT(), nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_tx_provider_event_not_null', 'transaction', ['provider', 'provider_event_id'], unique=1, sqlite_where=sa.text('provider_event_id IS NOT NULL'))
    op.create_index('ux_tx_player_id_idempotency_key_not_null', 'transaction', ['player_id', 'idempotency_key'], unique=1, sqlite_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('chargebackcase',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), nullable=False),
    sa.Column('reason_code', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('evidence_files', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('walletbalance',
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('player_id', sa.VARCHAR(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('balance_real_available', sa.FLOAT(), nullable=False),
    sa.Column('balance_real_pending', sa.FLOAT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'player_id', 'currency')
    )
    op.create_index('ix_walletbalance_updated_at', 'walletbalance', ['updated_at'], unique=False)
    op.create_table('contentpage',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliate',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('commission_rate', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonus',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('rules', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payoutattempt',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('withdraw_tx_id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('provider_event_id', sa.VARCHAR(), nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('error_code', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['withdraw_tx_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payoutattempt_withdraw_tx_id', 'payoutattempt', ['withdraw_tx_id'], unique=False)
    op.create_index('ix_payoutattempt_tenant_id', 'payoutattempt', ['tenant_id'], unique=False)
    op.create_index('ix_payoutattempt_status', 'payoutattempt', ['status'], unique=False)
    op.create_index('ix_payoutattempt_provider_event_id', 'payoutattempt', ['provider_event_id'], unique=False)
    op.create_index('ix_payoutattempt_provider', 'payoutattempt', ['provider'], unique=False)
    op.create_index('ix_payoutattempt_idempotency_key', 'payoutattempt', ['idempotency_key'], unique=False)
    op.create_table('reconciliationreport',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('provider_name', sa.VARCHAR(), nullable=False),
    sa.Column('period_start', sa.DATETIME(), nullable=False),
    sa.Column('period_end', sa.DATETIME(), nullable=False),
    sa.Column('total_records', sa.INTEGER(), nullable=False),
    sa.Column('mismatches', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('report_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledgertransaction',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tx_id', sa.VARCHAR(), nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('player_id', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('direction', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('provider_ref', sa.VARCHAR(), nullable=True),
    sa.Column('provider_event_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledgertransaction_tx_id', 'ledgertransaction', ['tx_id'], unique=False)
    op.create_index('ix_ledgertransaction_tenant_id', 'ledgertransaction', ['tenant_id'], unique=False)
    op.create_index('ix_ledgertransaction_player_id', 'ledgertransaction', ['player_id'], unique=False)
    op.create_index('ix_ledger_tx_tx_id', 'ledgertransaction', ['tx_id'], unique=False)
    op.create_index('ix_ledger_tx_provider_ref', 'ledgertransaction', ['provider_ref'], unique=False)
    op.create_index('ix_ledger_tx_player_created_at', 'ledgertransaction', ['player_id', 'created_at'], unique=False)
    op.create_table('adminuser',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_role', sa.VARCHAR(), nullable=True),
    sa.Column('is_platform_owner', sa.BOOLEAN(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('failed_login_attempts', sa.INTEGER(), nullable=False),
    sa.Column('invite_token', sa.VARCHAR(), nullable=True),
    sa.Column('password_reset_token', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_adminuser_tenant_id', 'adminuser', ['tenant_id'], unique=False)
    op.create_index('ix_adminuser_email', 'adminuser', ['email'], unique=False)
    op.create_table('game',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('rtp', sa.FLOAT(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('configuration', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financesettings',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('auto_payout_limit', sa.FLOAT(), nullable=False),
    sa.Column('provider_configs', sqlite.JSON(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('featureflag',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameconfigversion',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('game_id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('version', sa.VARCHAR(), nullable=False),
    sa.Column('config_snapshot', sqlite.JSON(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameasset',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('game_id', sa.VARCHAR(), nullable=False),
    sa.Column('asset_type', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
