"""T15_drift_fix_final_v2

Revision ID: 0968ae561847
Revises: 94870c5756db
Create Date: 2025-12-27 00:26:21.865617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0968ae561847'
down_revision: Union[str, None] = '94870c5756db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adminuser', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('affiliate', 'commission_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text('("CPA")'))
    op.alter_column('affiliate', 'cpa_amount',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('affiliate', 'cpa_threshold',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(20.0)'))
    op.alter_column('affiliate', 'revshare_percent',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
    op.drop_constraint(None, 'affiliate', type_='foreignkey')
    op.create_index(op.f('ix_auditevent_chain_id'), 'auditevent', ['chain_id'], unique=False)
    op.create_index(op.f('ix_auditevent_prev_row_hash'), 'auditevent', ['prev_row_hash'], unique=False)
    op.create_index(op.f('ix_auditevent_row_hash'), 'auditevent', ['row_hash'], unique=False)
    op.create_index(op.f('ix_auditevent_sequence'), 'auditevent', ['sequence'], unique=False)
    op.create_index(op.f('ix_auditevent_status'), 'auditevent', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditevent_status'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_sequence'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_row_hash'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_prev_row_hash'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_chain_id'), table_name='auditevent')
    op.create_foreign_key(None, 'affiliate', 'tenant', ['tenant_id'], ['id'])
    op.alter_column('affiliate', 'revshare_percent',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('affiliate', 'cpa_threshold',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(20.0)'))
    op.alter_column('affiliate', 'cpa_amount',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('affiliate', 'commission_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text('("CPA")'))
    op.alter_column('adminuser', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
