"""T15_drift_fix_final_v2

Revision ID: 0968ae561847
Revises: 94870c5756db
Create Date: 2025-12-27 00:26:21.865617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0968ae561847'
down_revision: Union[str, None] = '94870c5756db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. FIX ADMIN USER MFA (Nullable -> Not Null)
    # NOTE: Postgres boolean defaults must be true/false (not 0/1).
    with op.batch_alter_table('adminuser', schema=None) as batch_op:
        batch_op.alter_column(
            'mfa_enabled',
            existing_type=sa.BOOLEAN(),
            nullable=False,
            server_default=sa.text('false'),
        )

    # 2. FIX AFFILIATE (Nullable -> Not Null)
    with op.batch_alter_table('affiliate', schema=None) as batch_op:
        batch_op.alter_column('commission_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default='CPA') # Removed sa.text() and quoting
        batch_op.alter_column('cpa_amount',
               existing_type=sa.FLOAT(),
               nullable=False,
               server_default='0.0')
        batch_op.alter_column('cpa_threshold',
               existing_type=sa.FLOAT(),
               nullable=False,
               server_default='20.0')
        batch_op.alter_column('revshare_percent',
               existing_type=sa.FLOAT(),
               nullable=False,
               server_default='0.0')

    # 3. FIX AUDIT EVENT INDEXES
    def safe_create_index(index_name, table_name, columns):
        try:
            op.create_index(op.f(index_name), table_name, columns, unique=False)
        except Exception:
            pass 

    safe_create_index('ix_auditevent_chain_id', 'auditevent', ['chain_id'])
    safe_create_index('ix_auditevent_prev_row_hash', 'auditevent', ['prev_row_hash'])
    safe_create_index('ix_auditevent_row_hash', 'auditevent', ['row_hash'])
    safe_create_index('ix_auditevent_sequence', 'auditevent', ['sequence'])
    safe_create_index('ix_auditevent_status', 'auditevent', ['status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
