"""T13-001_schema_drift_reset_full

Revision ID: 3c4ee35573cd
Revises: 4de54ad60828
Create Date: 2025-12-27 00:07:49.900692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4ee35573cd'
down_revision: Union[str, None] = '4de54ad60828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokertable',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('limit_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('small_blind', sa.Float(), nullable=False),
    sa.Column('big_blind', sa.Float(), nullable=False),
    sa.Column('min_buyin', sa.Float(), nullable=False),
    sa.Column('max_buyin', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rake_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_players', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokertable_rake_profile_id'), 'pokertable', ['rake_profile_id'], unique=False)
    op.create_index(op.f('ix_pokertable_tenant_id'), 'pokertable', ['tenant_id'], unique=False)
    op.create_table('pokersession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buyin_total', sa.Float(), nullable=False),
    sa.Column('cashout_total', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['pokertable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokersession_player_id'), 'pokersession', ['player_id'], unique=False)
    op.create_index(op.f('ix_pokersession_table_id'), 'pokersession', ['table_id'], unique=False)
    op.create_index(op.f('ix_pokersession_tenant_id'), 'pokersession', ['tenant_id'], unique=False)
    op.drop_index('ix_table_game_tenant_id', table_name='table_game')
    op.drop_table('table_game')
    op.alter_column('adminuser', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('affiliate', 'commission_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text('("CPA")'))
    op.alter_column('affiliate', 'cpa_amount',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('affiliate', 'cpa_threshold',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(20.0)'))
    op.alter_column('affiliate', 'revshare_percent',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
    op.drop_constraint(None, 'affiliate', type_='foreignkey')
    op.alter_column('auditevent', 'actor_role',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'status',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'reason',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'before_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('auditevent', 'after_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('auditevent', 'diff_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('auditevent', 'metadata_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('auditevent', 'error_code',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'error_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'row_hash',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'prev_row_hash',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'chain_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_auditevent_chain_id'), 'auditevent', ['chain_id'], unique=False)
    op.create_index(op.f('ix_auditevent_prev_row_hash'), 'auditevent', ['prev_row_hash'], unique=False)
    op.create_index(op.f('ix_auditevent_row_hash'), 'auditevent', ['row_hash'], unique=False)
    op.create_index(op.f('ix_auditevent_sequence'), 'auditevent', ['sequence'], unique=False)
    op.create_index(op.f('ix_auditevent_status'), 'auditevent', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditevent_status'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_sequence'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_row_hash'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_prev_row_hash'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_chain_id'), table_name='auditevent')
    op.alter_column('auditevent', 'chain_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'prev_row_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'row_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'error_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'error_code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'metadata_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'diff_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'after_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'before_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'user_agent',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'reason',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'actor_role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(None, 'affiliate', 'tenant', ['tenant_id'], ['id'])
    op.alter_column('affiliate', 'revshare_percent',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('affiliate', 'cpa_threshold',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(20.0)'))
    op.alter_column('affiliate', 'cpa_amount',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('affiliate', 'commission_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text('("CPA")'))
    op.alter_column('adminuser', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table('table_game',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('min_bet', sa.FLOAT(), nullable=False),
    sa.Column('max_bet', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_table_game_tenant_id', 'table_game', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_pokersession_tenant_id'), table_name='pokersession')
    op.drop_index(op.f('ix_pokersession_table_id'), table_name='pokersession')
    op.drop_index(op.f('ix_pokersession_player_id'), table_name='pokersession')
    op.drop_table('pokersession')
    op.drop_index(op.f('ix_pokertable_tenant_id'), table_name='pokertable')
    op.drop_index(op.f('ix_pokertable_rake_profile_id'), table_name='pokertable')
    op.drop_table('pokertable')
    # ### end Alembic commands ###
