"""Add Robot Models Fixed

Revision ID: 4de54ad60828
Revises: edb937dfd5ea
Create Date: 2025-12-26 17:46:47.876975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4de54ad60828'
down_revision: Union[str, None] = 'edb937dfd5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_tenant_id'), 'apikey', ['tenant_id'], unique=False)
    op.create_table('auditevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditevent_action'), 'auditevent', ['action'], unique=False)
    op.create_index(op.f('ix_auditevent_actor_user_id'), 'auditevent', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_auditevent_request_id'), 'auditevent', ['request_id'], unique=False)
    op.create_index(op.f('ix_auditevent_resource_id'), 'auditevent', ['resource_id'], unique=False)
    op.create_index(op.f('ix_auditevent_resource_type'), 'auditevent', ['resource_type'], unique=False)
    op.create_index(op.f('ix_auditevent_result'), 'auditevent', ['result'], unique=False)
    op.create_index(op.f('ix_auditevent_tenant_id'), 'auditevent', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_auditevent_timestamp'), 'auditevent', ['timestamp'], unique=False)
    op.create_table('auditlog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('callbacknonce',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callbacknonce_nonce'), 'callbacknonce', ['nonce'], unique=False)
    op.create_index(op.f('ix_callbacknonce_provider_id'), 'callbacknonce', ['provider_id'], unique=False)
    op.create_table('featureflag',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mathasset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mathasset_ref_key'), 'mathasset', ['ref_key'], unique=True)
    op.create_table('robotdefinition',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('config_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robotdefinition_config_hash'), 'robotdefinition', ['config_hash'], unique=False)
    op.create_index(op.f('ix_robotdefinition_name'), 'robotdefinition', ['name'], unique=False)
    op.create_table('tenant',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('daily_deposit_limit', sa.Float(), nullable=True),
    sa.Column('daily_withdraw_limit', sa.Float(), nullable=True),
    sa.Column('payout_retry_limit', sa.Integer(), nullable=True),
    sa.Column('payout_cooldown_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=True)
    op.create_table('adminuser',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_platform_owner', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('invite_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminuser_email'), 'adminuser', ['email'], unique=True)
    op.create_index(op.f('ix_adminuser_tenant_id'), 'adminuser', ['tenant_id'], unique=False)
    op.create_table('affiliate',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_tenant_id'), 'affiliate', ['tenant_id'], unique=False)
    op.create_table('approvalrequest',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('related_entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requester_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvalrequest_tenant_id'), 'approvalrequest', ['tenant_id'], unique=False)
    op.create_table('bonus',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_tenant_id'), 'bonus', ['tenant_id'], unique=False)
    op.create_table('contentpage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentpage_tenant_id'), 'contentpage', ['tenant_id'], unique=False)
    op.create_table('financesettings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auto_payout_limit', sa.Float(), nullable=False),
    sa.Column('provider_configs', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financesettings_tenant_id'), 'financesettings', ['tenant_id'], unique=True)
    op.create_table('gameasset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gameasset_game_id'), 'gameasset', ['game_id'], unique=False)
    op.create_table('gameconfigversion',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gameconfigversion_game_id'), 'gameconfigversion', ['game_id'], unique=False)
    op.create_index(op.f('ix_gameconfigversion_tenant_id'), 'gameconfigversion', ['tenant_id'], unique=False)
    op.create_table('gamerobotbinding',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('robot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robotdefinition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamerobotbinding_game_id'), 'gamerobotbinding', ['game_id'], unique=False)
    op.create_index(op.f('ix_gamerobotbinding_tenant_id'), 'gamerobotbinding', ['tenant_id'], unique=False)
    op.create_table('player',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('balance_real', sa.Float(), nullable=False),
    sa.Column('balance_bonus', sa.Float(), nullable=False),
    sa.Column('wagering_requirement', sa.Float(), nullable=False),
    sa.Column('wagering_remaining', sa.Float(), nullable=False),
    sa.Column('balance_real_available', sa.Float(), nullable=False),
    sa.Column('balance_real_held', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kyc_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk_score', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_email'), 'player', ['email'], unique=False)
    op.create_index(op.f('ix_player_tenant_id'), 'player', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_player_username'), 'player', ['username'], unique=False)
    op.create_table('reconciliationreport',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('mismatches', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliationreport_tenant_id'), 'reconciliationreport', ['tenant_id'], unique=False)
    op.create_table('riskrule',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riskrule_tenant_id'), 'riskrule', ['tenant_id'], unique=False)
    op.create_table('supportticket',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supportticket_player_id'), 'supportticket', ['player_id'], unique=False)
    op.create_index(op.f('ix_supportticket_tenant_id'), 'supportticket', ['tenant_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_tx_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_player_id'), 'transaction', ['player_id'], unique=False)
    op.create_index(op.f('ix_transaction_tenant_id'), 'transaction', ['tenant_id'], unique=False)
    op.create_table('chargebackcase',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_files', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chargebackcase_tenant_id'), 'chargebackcase', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chargebackcase_transaction_id'), 'chargebackcase', ['transaction_id'], unique=False)
    op.create_table('payoutattempt',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('withdraw_tx_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['withdraw_tx_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payoutattempt_idempotency_key'), 'payoutattempt', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_payoutattempt_provider'), 'payoutattempt', ['provider'], unique=False)
    op.create_index(op.f('ix_payoutattempt_provider_event_id'), 'payoutattempt', ['provider_event_id'], unique=False)
    op.create_index(op.f('ix_payoutattempt_status'), 'payoutattempt', ['status'], unique=False)
    op.create_index(op.f('ix_payoutattempt_tenant_id'), 'payoutattempt', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_payoutattempt_withdraw_tx_id'), 'payoutattempt', ['withdraw_tx_id'], unique=False)
    op.add_column('game', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('game', sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('game', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('game', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('game', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('gameevent', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameevent', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.drop_column('game', 'image_url')
    op.drop_column('game', 'status')
    op.drop_column('game', 'category')
    op.drop_column('game', 'provider')
    op.drop_column('game', 'name')
    op.drop_index(op.f('ix_payoutattempt_withdraw_tx_id'), table_name='payoutattempt')
    op.drop_index(op.f('ix_payoutattempt_tenant_id'), table_name='payoutattempt')
    op.drop_index(op.f('ix_payoutattempt_status'), table_name='payoutattempt')
    op.drop_index(op.f('ix_payoutattempt_provider_event_id'), table_name='payoutattempt')
    op.drop_index(op.f('ix_payoutattempt_provider'), table_name='payoutattempt')
    op.drop_index(op.f('ix_payoutattempt_idempotency_key'), table_name='payoutattempt')
    op.drop_table('payoutattempt')
    op.drop_index(op.f('ix_chargebackcase_transaction_id'), table_name='chargebackcase')
    op.drop_index(op.f('ix_chargebackcase_tenant_id'), table_name='chargebackcase')
    op.drop_table('chargebackcase')
    op.drop_index(op.f('ix_transaction_tenant_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_player_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_supportticket_tenant_id'), table_name='supportticket')
    op.drop_index(op.f('ix_supportticket_player_id'), table_name='supportticket')
    op.drop_table('supportticket')
    op.drop_index(op.f('ix_riskrule_tenant_id'), table_name='riskrule')
    op.drop_table('riskrule')
    op.drop_index(op.f('ix_reconciliationreport_tenant_id'), table_name='reconciliationreport')
    op.drop_table('reconciliationreport')
    op.drop_index(op.f('ix_player_username'), table_name='player')
    op.drop_index(op.f('ix_player_tenant_id'), table_name='player')
    op.drop_index(op.f('ix_player_email'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_gamerobotbinding_tenant_id'), table_name='gamerobotbinding')
    op.drop_index(op.f('ix_gamerobotbinding_game_id'), table_name='gamerobotbinding')
    op.drop_table('gamerobotbinding')
    op.drop_index(op.f('ix_gameconfigversion_tenant_id'), table_name='gameconfigversion')
    op.drop_index(op.f('ix_gameconfigversion_game_id'), table_name='gameconfigversion')
    op.drop_table('gameconfigversion')
    op.drop_index(op.f('ix_gameasset_game_id'), table_name='gameasset')
    op.drop_table('gameasset')
    op.drop_index(op.f('ix_financesettings_tenant_id'), table_name='financesettings')
    op.drop_table('financesettings')
    op.drop_index(op.f('ix_contentpage_tenant_id'), table_name='contentpage')
    op.drop_table('contentpage')
    op.drop_index(op.f('ix_bonus_tenant_id'), table_name='bonus')
    op.drop_table('bonus')
    op.drop_index(op.f('ix_approvalrequest_tenant_id'), table_name='approvalrequest')
    op.drop_table('approvalrequest')
    op.drop_index(op.f('ix_affiliate_tenant_id'), table_name='affiliate')
    op.drop_table('affiliate')
    op.drop_index(op.f('ix_adminuser_tenant_id'), table_name='adminuser')
    op.drop_index(op.f('ix_adminuser_email'), table_name='adminuser')
    op.drop_table('adminuser')
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_robotdefinition_name'), table_name='robotdefinition')
    op.drop_index(op.f('ix_robotdefinition_config_hash'), table_name='robotdefinition')
    op.drop_table('robotdefinition')
    op.drop_index(op.f('ix_mathasset_ref_key'), table_name='mathasset')
    op.drop_table('mathasset')
    op.drop_table('featureflag')
    op.drop_index(op.f('ix_callbacknonce_provider_id'), table_name='callbacknonce')
    op.drop_index(op.f('ix_callbacknonce_nonce'), table_name='callbacknonce')
    op.drop_table('callbacknonce')
    op.drop_table('auditlog')
    op.drop_index(op.f('ix_auditevent_timestamp'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_tenant_id'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_result'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_resource_type'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_resource_id'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_request_id'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_actor_user_id'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_action'), table_name='auditevent')
    op.drop_table('auditevent')
    op.drop_index(op.f('ix_apikey_tenant_id'), table_name='apikey')
    op.drop_table('apikey')
    # ### end Alembic commands ###
