"""Register Game Models Fixed 2

Revision ID: 6512f9dafb83
Revises: 079ecae04f90
Create Date: 2025-12-26 17:30:01.317685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel 
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '6512f9dafb83'
down_revision: Union[str, None] = '079ecae04f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(table_name):
    bind = op.get_bind()
    insp = inspect(bind)
    return insp.has_table(table_name)

def get_indexes(table_name):
    bind = op.get_bind()
    insp = inspect(bind)
    return [i['name'] for i in insp.get_indexes(table_name)]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Safe create for all tables
    
    if not table_exists('apikey'):
        op.create_table('apikey',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_apikey_tenant_id'), 'apikey', ['tenant_id'], unique=False)

    if not table_exists('auditevent'):
        op.create_table('auditevent',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('actor_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_auditevent_action'), 'auditevent', ['action'], unique=False)
        op.create_index(op.f('ix_auditevent_actor_user_id'), 'auditevent', ['actor_user_id'], unique=False)
        op.create_index(op.f('ix_auditevent_request_id'), 'auditevent', ['request_id'], unique=False)
        op.create_index(op.f('ix_auditevent_resource_id'), 'auditevent', ['resource_id'], unique=False)
        op.create_index(op.f('ix_auditevent_resource_type'), 'auditevent', ['resource_type'], unique=False)
        op.create_index(op.f('ix_auditevent_result'), 'auditevent', ['result'], unique=False)
        op.create_index(op.f('ix_auditevent_tenant_id'), 'auditevent', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_auditevent_timestamp'), 'auditevent', ['timestamp'], unique=False)

    if not table_exists('auditlog'):
        op.create_table('auditlog',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )

    if not table_exists('featureflag'):
        op.create_table('featureflag',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )

    if not table_exists('game'):
        op.create_table('game',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('rtp', sa.Float(), nullable=False),
        sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('configuration', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_game_external_id'), 'game', ['external_id'], unique=False)
        op.create_index(op.f('ix_game_provider_id'), 'game', ['provider_id'], unique=False)
        op.create_index(op.f('ix_game_tenant_id'), 'game', ['tenant_id'], unique=False)

    if not table_exists('tenant'):
        op.create_table('tenant',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('features', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('daily_deposit_limit', sa.Float(), nullable=True),
        sa.Column('daily_withdraw_limit', sa.Float(), nullable=True),
        sa.Column('payout_retry_limit', sa.Integer(), nullable=True),
        sa.Column('payout_cooldown_seconds', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=True)

    if not table_exists('adminuser'):
        op.create_table('adminuser',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_platform_owner', sa.Boolean(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
        sa.Column('invite_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('password_reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_adminuser_email'), 'adminuser', ['email'], unique=True)
        op.create_index(op.f('ix_adminuser_tenant_id'), 'adminuser', ['tenant_id'], unique=False)

    if not table_exists('affiliate'):
        op.create_table('affiliate',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('commission_rate', sa.Float(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_affiliate_tenant_id'), 'affiliate', ['tenant_id'], unique=False)

    if not table_exists('approvalrequest'):
        op.create_table('approvalrequest',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('related_entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('requester_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_approvalrequest_tenant_id'), 'approvalrequest', ['tenant_id'], unique=False)

    if not table_exists('bonus'):
        op.create_table('bonus',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('rules', sa.JSON(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_bonus_tenant_id'), 'bonus', ['tenant_id'], unique=False)

    if not table_exists('contentpage'):
        op.create_table('contentpage',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_contentpage_tenant_id'), 'contentpage', ['tenant_id'], unique=False)

    if not table_exists('financesettings'):
        op.create_table('financesettings',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('auto_payout_limit', sa.Float(), nullable=False),
        sa.Column('provider_configs', sa.JSON(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_financesettings_tenant_id'), 'financesettings', ['tenant_id'], unique=True)

    if not table_exists('gameasset'):
        op.create_table('gameasset',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_gameasset_game_id'), 'gameasset', ['game_id'], unique=False)

    if not table_exists('gameconfigversion'):
        op.create_table('gameconfigversion',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('config_snapshot', sa.JSON(), nullable=True),
        sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_gameconfigversion_game_id'), 'gameconfigversion', ['game_id'], unique=False)
        op.create_index(op.f('ix_gameconfigversion_tenant_id'), 'gameconfigversion', ['tenant_id'], unique=False)


    # FIX: robotdefinition must exist before gamerobotbinding FK
    if not table_exists('robotdefinition'):
        op.create_table(
            'robotdefinition',
            sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('config', sa.JSON(), nullable=True),
            sa.Column('config_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_robotdefinition_name'), 'robotdefinition', ['name'], unique=False)
        op.create_index(op.f('ix_robotdefinition_config_hash'), 'robotdefinition', ['config_hash'], unique=False)

    if not table_exists('gamerobotbinding'):
        op.create_table('gamerobotbinding',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('robot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('effective_from', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['robot_id'], ['robotdefinition.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_gamerobotbinding_game_id'), 'gamerobotbinding', ['game_id'], unique=False)
        op.create_index(op.f('ix_gamerobotbinding_tenant_id'), 'gamerobotbinding', ['tenant_id'], unique=False)

    if not table_exists('player'):
        op.create_table('player',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('balance_real', sa.Float(), nullable=False),
        sa.Column('balance_bonus', sa.Float(), nullable=False),
        sa.Column('wagering_requirement', sa.Float(), nullable=False),
        sa.Column('wagering_remaining', sa.Float(), nullable=False),
        sa.Column('balance_real_available', sa.Float(), nullable=False),
        sa.Column('balance_real_held', sa.Float(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('kyc_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('risk_score', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('registered_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_player_email'), 'player', ['email'], unique=False)
        op.create_index(op.f('ix_player_tenant_id'), 'player', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_player_username'), 'player', ['username'], unique=False)

    if not table_exists('reconciliationreport'):
        op.create_table('reconciliationreport',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('provider_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('period_start', sa.DateTime(), nullable=False),
        sa.Column('period_end', sa.DateTime(), nullable=False),
        sa.Column('total_records', sa.Integer(), nullable=False),
        sa.Column('mismatches', sa.Integer(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('report_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_reconciliationreport_tenant_id'), 'reconciliationreport', ['tenant_id'], unique=False)

    if not table_exists('riskrule'):
        op.create_table('riskrule',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_riskrule_tenant_id'), 'riskrule', ['tenant_id'], unique=False)

    if not table_exists('supportticket'):
        op.create_table('supportticket',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('messages', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_supportticket_player_id'), 'supportticket', ['player_id'], unique=False)
        op.create_index(op.f('ix_supportticket_tenant_id'), 'supportticket', ['tenant_id'], unique=False)

    if not table_exists('transaction'):
        op.create_table('transaction',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('provider_tx_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('provider_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('review_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(), nullable=True),
        sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
        sa.Column('balance_after', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_transaction_player_id'), 'transaction', ['player_id'], unique=False)
        op.create_index(op.f('ix_transaction_tenant_id'), 'transaction', ['tenant_id'], unique=False)

    if not table_exists('chargebackcase'):
        op.create_table('chargebackcase',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('evidence_files', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_chargebackcase_tenant_id'), 'chargebackcase', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_chargebackcase_transaction_id'), 'chargebackcase', ['transaction_id'], unique=False)


    # FIX: gamesession + gameround must exist before gameevent FK (round_id -> gameround.id)
    if not table_exists('gamesession'):
        op.create_table(
            'gamesession',
            sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('provider_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('last_activity_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
            sa.ForeignKeyConstraint(['game_id'], ['game.id']),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_gamesession_tenant_id'), 'gamesession', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_gamesession_player_id'), 'gamesession', ['player_id'], unique=False)
        op.create_index(op.f('ix_gamesession_provider_session_id'), 'gamesession', ['provider_session_id'], unique=False)

    if not table_exists('gameround'):
        op.create_table(
            'gameround',
            sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('provider_round_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('total_bet', sa.Float(), nullable=False),
            sa.Column('total_win', sa.Float(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
            sa.ForeignKeyConstraint(['session_id'], ['gamesession.id']),
            sa.ForeignKeyConstraint(['game_id'], ['game.id']),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_gameround_tenant_id'), 'gameround', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_gameround_provider_round_id'), 'gameround', ['provider_round_id'], unique=False)
        op.create_index(op.f('ix_gameround_session_id'), 'gameround', ['session_id'], unique=False)
        op.create_index(op.f('ix_gameround_game_id'), 'gameround', ['game_id'], unique=False)

    if not table_exists('gameevent'):
        op.create_table('gameevent',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('round_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('provider_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tx_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        # Removed created_at since it caused drop_column issue later
        sa.ForeignKeyConstraint(['round_id'], ['gameround.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_gameevent_provider_event_id'), 'gameevent', ['provider_event_id'], unique=True)
        op.create_index(op.f('ix_gameevent_round_id'), 'gameevent', ['round_id'], unique=False)
        op.create_index(op.f('ix_gameevent_tx_id'), 'gameevent', ['tx_id'], unique=False)

    if not table_exists('payoutattempt'):
        op.create_table('payoutattempt',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('withdraw_tx_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('provider_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.ForeignKeyConstraint(['withdraw_tx_id'], ['transaction.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_payoutattempt_idempotency_key'), 'payoutattempt', ['idempotency_key'], unique=False)
        op.create_index(op.f('ix_payoutattempt_provider'), 'payoutattempt', ['provider'], unique=False)
        op.create_index(op.f('ix_payoutattempt_provider_event_id'), 'payoutattempt', ['provider_event_id'], unique=False)
        op.create_index(op.f('ix_payoutattempt_status'), 'payoutattempt', ['status'], unique=False)
        op.create_index(op.f('ix_payoutattempt_tenant_id'), 'payoutattempt', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_payoutattempt_withdraw_tx_id'), 'payoutattempt', ['withdraw_tx_id'], unique=False)
    
    # Check if 'gameevent' exists and has 'created_at' column before dropping
    if table_exists('gameevent'):
        columns = [c['name'] for c in inspect(op.get_bind()).get_columns('gameevent')]
        if 'created_at' in columns:
            op.drop_column('gameevent', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrade logic skipped
    pass
