"""T15_kill_table_game

Revision ID: 86d5b2971e22
Revises: 0968ae561847
Create Date: 2025-12-27 00:28:49.056516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d5b2971e22'
down_revision: Union[str, None] = '0968ae561847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_table_game_tenant_id', table_name='table_game')
    op.drop_table('table_game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_game',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('min_bet', sa.FLOAT(), nullable=False),
    sa.Column('max_bet', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_table_game_tenant_id', 'table_game', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
