"""T15_kill_table_game

Revision ID: 86d5b2971e22
Revises: 0968ae561847
Create Date: 2025-12-27 00:28:49.056516

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '86d5b2971e22'
down_revision: Union[str, None] = '0968ae561847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(table_name):
    bind = op.get_bind()
    insp = inspect(bind)
    return insp.has_table(table_name)

def get_indexes(table_name):
    bind = op.get_bind()
    insp = inspect(bind)
    return [i['name'] for i in insp.get_indexes(table_name)]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists('table_game'):
        indexes = get_indexes('table_game')
        if 'ix_table_game_tenant_id' in indexes:
            op.drop_index('ix_table_game_tenant_id', table_name='table_game')
        op.drop_table('table_game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipping recreate for simplicity in fix
    pass
    # ### end Alembic commands ###
