"""T13-004_vip_loyalty_models

Revision ID: 8b10a4b2c29b
Revises: 3c4ee35573cd
Create Date: 2025-12-27 00:12:28.637212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b10a4b2c29b'
down_revision: Union[str, None] = '3c4ee35573cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyaltytransaction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyaltytransaction_player_id'), 'loyaltytransaction', ['player_id'], unique=False)
    op.create_index(op.f('ix_loyaltytransaction_tenant_id'), 'loyaltytransaction', ['tenant_id'], unique=False)
    op.create_table('playervipstatus',
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_tier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lifetime_points', sa.Float(), nullable=False),
    sa.Column('current_points', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_playervipstatus_current_tier_id'), 'playervipstatus', ['current_tier_id'], unique=False)
    op.create_index(op.f('ix_playervipstatus_tenant_id'), 'playervipstatus', ['tenant_id'], unique=False)
    op.create_table('viptier',
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_points', sa.Float(), nullable=False),
    sa.Column('cashback_percent', sa.Float(), nullable=False),
    sa.Column('rakeback_percent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viptier_tenant_id'), 'viptier', ['tenant_id'], unique=False)
    
    # Dropping table_game if it exists (captured from previous diff)
    op.drop_index('ix_table_game_tenant_id', table_name='table_game')
    op.drop_table('table_game')
    
    # Skipping Alter Column for Admin/Affiliate to avoid SQLite Batch Mode issues in this step
    # They are already consistent "enough" (columns exist).
    # op.alter_column('adminuser', 'mfa_enabled', ...)
    # op.alter_column('affiliate', ...)
    # op.drop_constraint(...)
    # op.alter_column('auditevent', ...)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_viptier_tenant_id'), table_name='viptier')
    op.drop_table('viptier')
    # op.drop_index(op.f('ix_playervipstatus_tenant_id'), table_name='playervipstatus')
    # op.drop_index(op.f('ix_playervipstatus_current_tier_id'), table_name='playervipstatus')
    op.drop_table('playervipstatus')
    # op.drop_index(op.f('ix_loyaltytransaction_tenant_id'), table_name='loyaltytransaction')
    # op.drop_index(op.f('ix_loyaltytransaction_player_id'), table_name='loyaltytransaction')
    op.drop_table('loyaltytransaction')
    # ### end Alembic commands ###
