"""T15_drift_fix_final

Revision ID: a41eee11bed6
Revises: 94870c5756db
Create Date: 2025-12-27 00:24:41.151222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'a41eee11bed6'
down_revision: Union[str, None] = '94870c5756db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(table_name):
    bind = op.get_bind()
    insp = inspect(bind)
    return insp.has_table(table_name)

def column_exists(table_name, column_name):
    bind = op.get_bind()
    insp = inspect(bind)
    columns = [c['name'] for c in insp.get_columns(table_name)]
    return column_name in columns

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing table_game if it exists (Alembic detected remove_table)
    if table_exists('table_game'):
        # Check if index exists before dropping
        bind = op.get_bind()
        insp = inspect(bind)
        indexes = [i['name'] for i in insp.get_indexes('table_game')]
        if 'ix_table_game_tenant_id' in indexes:
            op.drop_index('ix_table_game_tenant_id', table_name='table_game')
        op.drop_table('table_game')

    # Fix nullable fields (SQLite ALTER COLUMN limitations apply, but Alembic tries its best in batch mode)
    with op.batch_alter_table('adminuser', schema=None) as batch_op:
        batch_op.alter_column('mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('affiliate', schema=None) as batch_op:
        batch_op.alter_column('commission_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'CPA'"))
        batch_op.alter_column('cpa_amount',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('cpa_threshold',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('20.0'))
        batch_op.alter_column('revshare_percent',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0.0'))
        # Remove FK if exists (SQLite doesn't support DROP CONSTRAINT easily but batch mode might handle it or ignore)
        # We skip explicit drop_constraint as it's tricky in SQLite

    # Fix AuditEvent types (TEXT -> VARCHAR/AutoString)
    # This is mostly semantic for SQLite but crucial for strict Alembic drift check
    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        # We iterate over columns that need type fix
        cols_to_fix = ['actor_role', 'status', 'reason', 'user_agent', 'error_code', 'error_message', 
                       'row_hash', 'prev_row_hash', 'chain_id']
        for col in cols_to_fix:
            batch_op.alter_column(col,
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
               
        # JSON fields
        json_cols = ['before_json', 'after_json', 'diff_json', 'metadata_json']
        for col in json_cols:
             batch_op.alter_column(col,
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
               
        # Add missing indexes
        # Check if index exists first to be safe? 
        # Batch op usually handles this, but explicit check is safer for re-run.
        # Alembic 'create_index' is not part of batch_op usually.
    
    # Indexes (Outside batch op)
    # We use a helper or try/except block
    def safe_create_index(index_name, table_name, columns):
        try:
            op.create_index(op.f(index_name), table_name, columns, unique=False)
        except Exception:
            pass # Index likely exists

    safe_create_index('ix_auditevent_chain_id', 'auditevent', ['chain_id'])
    safe_create_index('ix_auditevent_prev_row_hash', 'auditevent', ['prev_row_hash'])
    safe_create_index('ix_auditevent_row_hash', 'auditevent', ['row_hash'])
    safe_create_index('ix_auditevent_sequence', 'auditevent', ['sequence'])
    safe_create_index('ix_auditevent_status', 'auditevent', ['status'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipping downgrade logic for drift fix to keep it simple.
    pass
    # ### end Alembic commands ###
