"""T13-001_schema_drift_reset

Revision ID: a944d5072dab
Revises: 4de54ad60828
Create Date: 2025-12-27 00:06:46.145798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a944d5072dab'
down_revision: Union[str, None] = '4de54ad60828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tournamentregistration_player_id', table_name='tournamentregistration')
    op.drop_index('ix_tournamentregistration_tenant_id', table_name='tournamentregistration')
    op.drop_index('ix_tournamentregistration_tournament_id', table_name='tournamentregistration')
    op.drop_table('tournamentregistration')
    op.drop_index('ix_paymentintent_idempotency_key', table_name='paymentintent')
    op.drop_index('ix_paymentintent_player_id', table_name='paymentintent')
    op.drop_index('ix_paymentintent_tenant_id', table_name='paymentintent')
    op.drop_table('paymentintent')
    op.drop_index('ix_routingrule_tenant_id', table_name='routingrule')
    op.drop_table('routingrule')
    op.drop_index('ix_pokertournament_status', table_name='pokertournament')
    op.drop_index('ix_pokertournament_tenant_id', table_name='pokertournament')
    op.drop_table('pokertournament')
    op.drop_index('ix_playerkyc_player_id', table_name='playerkyc')
    op.drop_index('ix_playerkyc_tenant_id', table_name='playerkyc')
    op.drop_table('playerkyc')
    op.drop_index('ix_enginestandardprofile_code', table_name='enginestandardprofile')
    op.drop_table('enginestandardprofile')
    op.drop_index('ix_risksignal_player_id', table_name='risksignal')
    op.drop_index('ix_risksignal_tenant_id', table_name='risksignal')
    op.drop_table('risksignal')
    op.drop_index('ix_paymentattempt_payment_intent_id', table_name='paymentattempt')
    op.drop_index('ix_paymentattempt_provider', table_name='paymentattempt')
    op.drop_index('ix_paymentattempt_tenant_id', table_name='paymentattempt')
    op.drop_table('paymentattempt')
    op.drop_index('ix_playerrgprofile_player_id', table_name='playerrgprofile')
    op.drop_index('ix_playerrgprofile_tenant_id', table_name='playerrgprofile')
    op.drop_table('playerrgprofile')
    op.drop_index('ix_reconciliation_runs_idempotency_key', table_name='reconciliation_runs')
    op.drop_index('ix_reconciliation_runs_provider', table_name='reconciliation_runs')
    op.drop_index('ix_reconciliation_runs_status', table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index('ix_dispute_payment_intent_id', table_name='dispute')
    op.drop_index('ix_dispute_tenant_id', table_name='dispute')
    op.drop_table('dispute')
    op.drop_index('ix_rakeprofile_name', table_name='rakeprofile')
    op.drop_index('ix_rakeprofile_tenant_id', table_name='rakeprofile')
    op.drop_table('rakeprofile')
    op.drop_index('ix_table_game_tenant_id', table_name='table_game')
    op.drop_table('table_game')
    op.drop_index('ix_pokerhandaudit_provider_hand_id', table_name='pokerhandaudit')
    op.drop_index('ix_pokerhandaudit_tenant_id', table_name='pokerhandaudit')
    op.drop_table('pokerhandaudit')
    op.alter_column('adminuser', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('affiliate', 'commission_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text('("CPA")'))
    op.alter_column('affiliate', 'cpa_amount',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('affiliate', 'cpa_threshold',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(20.0)'))
    op.alter_column('affiliate', 'revshare_percent',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
    op.drop_constraint(None, 'affiliate', type_='foreignkey')
    op.alter_column('auditevent', 'actor_role',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'status',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'reason',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'before_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('auditevent', 'after_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('auditevent', 'diff_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('auditevent', 'metadata_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('auditevent', 'error_code',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'error_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'row_hash',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'prev_row_hash',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('auditevent', 'chain_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_auditevent_chain_id'), 'auditevent', ['chain_id'], unique=False)
    op.create_index(op.f('ix_auditevent_prev_row_hash'), 'auditevent', ['prev_row_hash'], unique=False)
    op.create_index(op.f('ix_auditevent_row_hash'), 'auditevent', ['row_hash'], unique=False)
    op.create_index(op.f('ix_auditevent_sequence'), 'auditevent', ['sequence'], unique=False)
    op.create_index(op.f('ix_auditevent_status'), 'auditevent', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditevent_status'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_sequence'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_row_hash'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_prev_row_hash'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_chain_id'), table_name='auditevent')
    op.alter_column('auditevent', 'chain_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'prev_row_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'row_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'error_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'error_code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'metadata_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'diff_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'after_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'before_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'user_agent',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'reason',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditevent', 'actor_role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(None, 'affiliate', 'tenant', ['tenant_id'], ['id'])
    op.alter_column('affiliate', 'revshare_percent',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('affiliate', 'cpa_threshold',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(20.0)'))
    op.alter_column('affiliate', 'cpa_amount',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('affiliate', 'commission_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text('("CPA")'))
    op.alter_column('adminuser', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table('pokerhandaudit',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('provider_hand_id', sa.VARCHAR(), nullable=False),
    sa.Column('table_id', sa.VARCHAR(), nullable=False),
    sa.Column('game_type', sa.VARCHAR(), nullable=False),
    sa.Column('pot_total', sa.FLOAT(), nullable=False),
    sa.Column('rake_collected', sa.FLOAT(), nullable=False),
    sa.Column('rake_profile_id', sa.VARCHAR(), nullable=True),
    sa.Column('winners', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['rake_profile_id'], ['rakeprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pokerhandaudit_tenant_id', 'pokerhandaudit', ['tenant_id'], unique=False)
    op.create_index('ix_pokerhandaudit_provider_hand_id', 'pokerhandaudit', ['provider_hand_id'], unique=False)
    op.create_table('table_game',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('min_bet', sa.FLOAT(), nullable=False),
    sa.Column('max_bet', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_table_game_tenant_id', 'table_game', ['tenant_id'], unique=False)
    op.create_table('rakeprofile',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('game_type', sa.VARCHAR(), nullable=False),
    sa.Column('percentage', sa.FLOAT(), nullable=False),
    sa.Column('cap', sa.FLOAT(), nullable=False),
    sa.Column('rules', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rakeprofile_tenant_id', 'rakeprofile', ['tenant_id'], unique=False)
    op.create_index('ix_rakeprofile_name', 'rakeprofile', ['name'], unique=False)
    op.create_table('dispute',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('payment_intent_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('reason_code', sa.VARCHAR(), nullable=True),
    sa.Column('amount_disputed', sa.FLOAT(), nullable=False),
    sa.Column('evidence', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['paymentintent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dispute_tenant_id', 'dispute', ['tenant_id'], unique=False)
    op.create_index('ix_dispute_payment_intent_id', 'dispute', ['payment_intent_id'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('window_start', sa.DATETIME(), nullable=False),
    sa.Column('window_end', sa.DATETIME(), nullable=False),
    sa.Column('dry_run', sa.BOOLEAN(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(), nullable=True),
    sa.Column('stats_json', sqlite.JSON(), nullable=True),
    sa.Column('error_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reconciliation_runs_status', 'reconciliation_runs', ['status'], unique=False)
    op.create_index('ix_reconciliation_runs_provider', 'reconciliation_runs', ['provider'], unique=False)
    op.create_index('ix_reconciliation_runs_idempotency_key', 'reconciliation_runs', ['idempotency_key'], unique=False)
    op.create_table('playerrgprofile',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('player_id', sa.VARCHAR(), nullable=False),
    sa.Column('deposit_limit_daily', sa.FLOAT(), nullable=True),
    sa.Column('deposit_limit_weekly', sa.FLOAT(), nullable=True),
    sa.Column('deposit_limit_monthly', sa.FLOAT(), nullable=True),
    sa.Column('loss_limit_daily', sa.FLOAT(), nullable=True),
    sa.Column('loss_limit_weekly', sa.FLOAT(), nullable=True),
    sa.Column('session_time_limit_minutes', sa.INTEGER(), nullable=True),
    sa.Column('reality_check_interval_minutes', sa.INTEGER(), nullable=True),
    sa.Column('cool_off_until', sa.DATETIME(), nullable=True),
    sa.Column('self_excluded_until', sa.DATETIME(), nullable=True),
    sa.Column('self_excluded_permanent', sa.BOOLEAN(), nullable=False),
    sa.Column('last_reality_check_ack', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_playerrgprofile_tenant_id', 'playerrgprofile', ['tenant_id'], unique=False)
    op.create_index('ix_playerrgprofile_player_id', 'playerrgprofile', ['player_id'], unique=1)
    op.create_table('paymentattempt',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('payment_intent_id', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('attempt_no', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('raw_code', sa.VARCHAR(), nullable=True),
    sa.Column('retryable', sa.BOOLEAN(), nullable=False),
    sa.Column('latency_ms', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['paymentintent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paymentattempt_tenant_id', 'paymentattempt', ['tenant_id'], unique=False)
    op.create_index('ix_paymentattempt_provider', 'paymentattempt', ['provider'], unique=False)
    op.create_index('ix_paymentattempt_payment_intent_id', 'paymentattempt', ['payment_intent_id'], unique=False)
    op.create_table('risksignal',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('player_id', sa.VARCHAR(), nullable=True),
    sa.Column('target_resource_type', sa.VARCHAR(), nullable=True),
    sa.Column('target_resource_id', sa.VARCHAR(), nullable=True),
    sa.Column('signal_type', sa.VARCHAR(), nullable=False),
    sa.Column('severity', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('evidence_payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risksignal_tenant_id', 'risksignal', ['tenant_id'], unique=False)
    op.create_index('ix_risksignal_player_id', 'risksignal', ['player_id'], unique=False)
    op.create_table('enginestandardprofile',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('game_type', sa.VARCHAR(), nullable=False),
    sa.Column('config', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enginestandardprofile_code', 'enginestandardprofile', ['code'], unique=1)
    op.create_table('playerkyc',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('player_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('required_level', sa.VARCHAR(), nullable=False),
    sa.Column('provider_ref', sa.VARCHAR(), nullable=True),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.Column('rejection_reason', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_playerkyc_tenant_id', 'playerkyc', ['tenant_id'], unique=False)
    op.create_index('ix_playerkyc_player_id', 'playerkyc', ['player_id'], unique=1)
    op.create_table('pokertournament',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('game_type', sa.VARCHAR(), nullable=False),
    sa.Column('limit_type', sa.VARCHAR(), nullable=False),
    sa.Column('buy_in', sa.FLOAT(), nullable=False),
    sa.Column('fee', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('guaranteed_prize', sa.FLOAT(), nullable=True),
    sa.Column('starting_chips', sa.INTEGER(), nullable=False),
    sa.Column('min_players', sa.INTEGER(), nullable=False),
    sa.Column('max_players', sa.INTEGER(), nullable=False),
    sa.Column('start_at', sa.DATETIME(), nullable=False),
    sa.Column('late_reg_until', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('prize_pool_total', sa.FLOAT(), nullable=False),
    sa.Column('entrants_count', sa.INTEGER(), nullable=False),
    sa.Column('payout_report', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pokertournament_tenant_id', 'pokertournament', ['tenant_id'], unique=False)
    op.create_index('ix_pokertournament_status', 'pokertournament', ['status'], unique=False)
    op.create_table('routingrule',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('method', sa.VARCHAR(), nullable=True),
    sa.Column('bin_prefix', sa.VARCHAR(), nullable=True),
    sa.Column('provider_priority', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routingrule_tenant_id', 'routingrule', ['tenant_id'], unique=False)
    op.create_table('paymentintent',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('player_id', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(), nullable=False),
    sa.Column('current_provider', sa.VARCHAR(), nullable=True),
    sa.Column('attempts', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paymentintent_tenant_id', 'paymentintent', ['tenant_id'], unique=False)
    op.create_index('ix_paymentintent_player_id', 'paymentintent', ['player_id'], unique=False)
    op.create_index('ix_paymentintent_idempotency_key', 'paymentintent', ['idempotency_key'], unique=1)
    op.create_table('tournamentregistration',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('tournament_id', sa.VARCHAR(), nullable=False),
    sa.Column('player_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('buyin_amount', sa.FLOAT(), nullable=False),
    sa.Column('fee_amount', sa.FLOAT(), nullable=False),
    sa.Column('registered_at', sa.DATETIME(), nullable=False),
    sa.Column('tx_ref_buyin', sa.VARCHAR(), nullable=False),
    sa.Column('tx_ref_fee', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['pokertournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tournamentregistration_tournament_id', 'tournamentregistration', ['tournament_id'], unique=False)
    op.create_index('ix_tournamentregistration_tenant_id', 'tournamentregistration', ['tenant_id'], unique=False)
    op.create_index('ix_tournamentregistration_player_id', 'tournamentregistration', ['player_id'], unique=False)
    # ### end Alembic commands ###
