"""walletbalance add bonus columns

Revision ID: bee7653042ae
Revises: 20260102_04
Create Date: 2026-01-17 23:17:37.500077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee7653042ae'
down_revision: Union[str, None] = '20260102_04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokertable',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('limit_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('small_blind', sa.Float(), nullable=False),
    sa.Column('big_blind', sa.Float(), nullable=False),
    sa.Column('min_buyin', sa.Float(), nullable=False),
    sa.Column('max_buyin', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rake_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_players', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokertable_rake_profile_id'), 'pokertable', ['rake_profile_id'], unique=False)
    op.create_index(op.f('ix_pokertable_tenant_id'), 'pokertable', ['tenant_id'], unique=False)
    op.create_table('pokersession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buyin_total', sa.Float(), nullable=False),
    sa.Column('cashout_total', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['pokertable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokersession_player_id'), 'pokersession', ['player_id'], unique=False)
    op.create_index(op.f('ix_pokersession_table_id'), 'pokersession', ['table_id'], unique=False)
    op.create_index(op.f('ix_pokersession_tenant_id'), 'pokersession', ['tenant_id'], unique=False)
    op.drop_index('ix_table_game_tenant_id', table_name='table_game')
    op.drop_table('table_game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_game',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('min_bet', sa.FLOAT(), nullable=False),
    sa.Column('max_bet', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_table_game_tenant_id', 'table_game', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_pokersession_tenant_id'), table_name='pokersession')
    op.drop_index(op.f('ix_pokersession_table_id'), table_name='pokersession')
    op.drop_index(op.f('ix_pokersession_player_id'), table_name='pokersession')
    op.drop_table('pokersession')
    op.drop_index(op.f('ix_pokertable_tenant_id'), table_name='pokertable')
    op.drop_index(op.f('ix_pokertable_rake_profile_id'), table_name='pokertable')
    op.drop_table('pokertable')
    # ### end Alembic commands ###
