"""T17_dispute_models

Revision ID: c553520d78cd
Revises: 3daaf783771d
Create Date: 2025-12-27 01:02:09.969919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'c553520d78cd'
down_revision: Union[str, None] = '3daaf783771d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(table_name):
    bind = op.get_bind()
    insp = inspect(bind)
    return insp.has_table(table_name)

def get_indexes(table_name):
    bind = op.get_bind()
    insp = inspect(bind)
    return [i['name'] for i in insp.get_indexes(table_name)]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Update Dispute table (It already exists from payment_models.py but schema changed significantly)
    # Since SQLite doesn't support DROP COLUMN easily, and we are changing FKs and columns drastically,
    # The best strategy for SQLite is Copy-and-Move (Batch).
    
    # However, 'dispute' table might have data. 
    # If we assume 'dispute' table was just a placeholder in 'payment_models.py' (it was), we can drop and recreate?
    # Or rely on batch operations.
    
    with op.batch_alter_table('dispute', schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='USD'))
        batch_op.add_column(sa.Column('evidence_files', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        
        # Drop old columns (SQLite batch mode handles this by recreating table)
        batch_op.drop_column('evidence')
        batch_op.drop_column('payment_intent_id')
        batch_op.drop_column('amount_disputed')
        
        # Indexes
        batch_op.drop_index('ix_dispute_payment_intent_id')
        batch_op.create_index(op.f('ix_dispute_player_id'), ['player_id'], unique=False)
        batch_op.create_index(op.f('ix_dispute_status'), ['status'], unique=False)
        batch_op.create_index(op.f('ix_dispute_transaction_id'), ['transaction_id'], unique=False)

    # 2. AffiliateClawback (New table, auto-generated was missing it???)
    # Wait, 'AffiliateClawback' was in 'dispute_models.py'. Did Alembic miss it?
    # Let's check imports in env.py. We added 'dispute_models'.
    # If Alembic didn't detect 'add_table' for 'affiliateclawback', maybe it exists?
    # Or maybe it wasn't picked up?
    # Ah, I see. 'affiliateclawback' was NOT in the detected changes list above!
    # "Detected added table" was missing. Why?
    # Maybe because I didn't save dispute_models.py correctly? Or import issue?
    # I wrote dispute_models.py. I updated env.py.
    # Let's manually add it here to be safe.
    
    if not table_exists('affiliateclawback'):
        op.create_table('affiliateclawback',
            sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('affiliate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('original_commission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('dispute_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('amount_reversed', sa.Float(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['dispute_id'], ['dispute.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_affiliateclawback_affiliate_id'), 'affiliateclawback', ['affiliate_id'], unique=False)
        op.create_index(op.f('ix_affiliateclawback_tenant_id'), 'affiliateclawback', ['tenant_id'], unique=False)

    if table_exists('table_game'):
        indexes = get_indexes('table_game')
        if 'ix_table_game_tenant_id' in indexes:
            op.drop_index('ix_table_game_tenant_id', table_name='table_game')
        op.drop_table('table_game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
