"""T17_dispute_models

Revision ID: c553520d78cd
Revises: 3daaf783771d
Create Date: 2025-12-27 01:02:09.969919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c553520d78cd'
down_revision: Union[str, None] = '3daaf783771d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_table_game_tenant_id', table_name='table_game')
    op.drop_table('table_game')
    op.add_column('dispute', sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('dispute', sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('dispute', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('dispute', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('dispute', sa.Column('evidence_files', sa.JSON(), nullable=True))
    op.add_column('dispute', sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_dispute_payment_intent_id', table_name='dispute')
    op.create_index(op.f('ix_dispute_player_id'), 'dispute', ['player_id'], unique=False)
    op.create_index(op.f('ix_dispute_status'), 'dispute', ['status'], unique=False)
    op.create_index(op.f('ix_dispute_transaction_id'), 'dispute', ['transaction_id'], unique=False)
    op.drop_constraint(None, 'dispute', type_='foreignkey')
    op.drop_column('dispute', 'evidence')
    op.drop_column('dispute', 'payment_intent_id')
    op.drop_column('dispute', 'amount_disputed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispute', sa.Column('amount_disputed', sa.FLOAT(), nullable=False))
    op.add_column('dispute', sa.Column('payment_intent_id', sa.VARCHAR(), nullable=False))
    op.add_column('dispute', sa.Column('evidence', sqlite.JSON(), nullable=True))
    op.create_foreign_key(None, 'dispute', 'paymentintent', ['payment_intent_id'], ['id'])
    op.drop_index(op.f('ix_dispute_transaction_id'), table_name='dispute')
    op.drop_index(op.f('ix_dispute_status'), table_name='dispute')
    op.drop_index(op.f('ix_dispute_player_id'), table_name='dispute')
    op.create_index('ix_dispute_payment_intent_id', 'dispute', ['payment_intent_id'], unique=False)
    op.drop_column('dispute', 'resolution_note')
    op.drop_column('dispute', 'evidence_files')
    op.drop_column('dispute', 'currency')
    op.drop_column('dispute', 'amount')
    op.drop_column('dispute', 'player_id')
    op.drop_column('dispute', 'transaction_id')
    op.create_table('table_game',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('min_bet', sa.FLOAT(), nullable=False),
    sa.Column('max_bet', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_table_game_tenant_id', 'table_game', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
