"""Add Robot Models Fixed

Revision ID: 4de54ad60828
Revises: edb937dfd5ea
Create Date: 2025-12-26 17:46:47.876975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '4de54ad60828'
down_revision: Union[str, None] = 'edb937dfd5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(table_name):
    bind = op.get_bind()
    insp = inspect(bind)
    return insp.has_table(table_name)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only creating NEW tables: mathasset, robotdefinition, gamerobotbinding
    if not table_exists('mathasset'):
        op.create_table('mathasset',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ref_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('content', sa.JSON(), nullable=True),
        sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_mathasset_ref_key'), 'mathasset', ['ref_key'], unique=True)

    if not table_exists('robotdefinition'):
        op.create_table('robotdefinition',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('config_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_robotdefinition_config_hash'), 'robotdefinition', ['config_hash'], unique=False)
        op.create_index(op.f('ix_robotdefinition_name'), 'robotdefinition', ['name'], unique=False)

    if not table_exists('gamerobotbinding'):
        op.create_table('gamerobotbinding',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('robot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('effective_from', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['robot_id'], ['robotdefinition.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_gamerobotbinding_game_id'), 'gamerobotbinding', ['game_id'], unique=False)
        op.create_index(op.f('ix_gamerobotbinding_tenant_id'), 'gamerobotbinding', ['tenant_id'], unique=False)
    # Skipping duplicates...


def downgrade() -> None:
    # Downgrade logic skipped
    pass
