"""T13-004_vip_loyalty_models

Revision ID: 8b10a4b2c29b
Revises: 3c4ee35573cd
Create Date: 2025-12-27 00:12:28.637212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '8b10a4b2c29b'
down_revision: Union[str, None] = '3c4ee35573cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(table_name):
    bind = op.get_bind()
    insp = inspect(bind)
    return insp.has_table(table_name)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('loyaltytransaction'):
        op.create_table('loyaltytransaction',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('balance_after', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_loyaltytransaction_player_id'), 'loyaltytransaction', ['player_id'], unique=False)
        op.create_index(op.f('ix_loyaltytransaction_tenant_id'), 'loyaltytransaction', ['tenant_id'], unique=False)
    
    if not table_exists('playervipstatus'):
        op.create_table('playervipstatus',
        sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('current_tier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('lifetime_points', sa.Float(), nullable=False),
        sa.Column('current_points', sa.Float(), nullable=False),
        sa.Column('last_updated', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('player_id')
        )
        op.create_index(op.f('ix_playervipstatus_current_tier_id'), 'playervipstatus', ['current_tier_id'], unique=False)
        op.create_index(op.f('ix_playervipstatus_tenant_id'), 'playervipstatus', ['tenant_id'], unique=False)
    
    if not table_exists('viptier'):
        op.create_table('viptier',
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('min_points', sa.Float(), nullable=False),
        sa.Column('cashback_percent', sa.Float(), nullable=False),
        sa.Column('rakeback_percent', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_viptier_tenant_id'), 'viptier', ['tenant_id'], unique=False)
    
    if table_exists('table_game'):
        op.drop_index('ix_table_game_tenant_id', table_name='table_game')
        op.drop_table('table_game')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
